using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TechHub.Core;

namespace TechHub.QuestionBank.Core.ViewModel;

/// <summary>
/// Sent by frontend after teacher finishes drawing
/// Frontend has already:
/// 1. Rendered all strokes to canvas
/// 2. Captured canvas as PNG
/// 3. Uploaded PNG to CDN
/// 4. Received CDN url back
/// Now tells backend to link everything to question
/// </summary>
public class AttachBoardSessionViewModel
{
	public Guid QuestionId { get; set; }

	public string BoardSessionId { get; set; }
	// MongoDB session ID
	// String not Guid because MongoDB
	// uses its own ID format

	public string SnapshotUrl { get; set; }
	// CDN url of PNG snapshot
	// Generated by frontend from canvas
	// Already uploaded before this call

	public string SnapshotPublicId { get; set; }
	// CDN public ID
	// Needed for deletion when detaching
	// Follows existing Cloudinary pattern
}

/// <summary>
/// Sent when teacher wants to remove
/// board content from a question
/// </summary>
public class DetachBoardSessionViewModel
{
	public Guid QuestionId { get; set; }
}

/// <summary>
/// Response after successful attachment
/// Frontend uses SnapshotUrl to display
/// board content immediately
/// </summary>
public class AttachBoardSessionResponse : BaseResponse
{
	public Guid QuestionId { get; set; }
	public string BoardSessionId { get; set; }
	public string SnapshotUrl { get; set; }
	// Frontend updates local question record
	// with these values immediately
	// Offline-first — local record updated
	// before next full sync
}

/// <summary>
/// Response containing board session
/// reference for editing purposes
/// Returns MongoDB session ID so
/// frontend can load strokes for editing
/// </summary>
public class BoardSessionResponse : BaseResponse
{
	public Guid QuestionId { get; set; }
	public string BoardSessionId { get; set; }
	// Frontend uses this to fetch
	// strokes from MongoDB directly
	// Backend does not return strokes
	// Only returns the reference
	public string SnapshotUrl { get; set; }
	public bool HasBoardSession { get; set; }
}

